In [1]:
#Expt 6 
#Data Analytics III

#mporting libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#import the dataset

dataset = pd.read_csv('D:\Sem 6\DSBDA Pract\Iris.csv')
X=dataset.iloc[:,:4].values 
y=dataset['Species'].values 
print(dataset.head(5))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [3]:
#Splitting the dataset into Training set and Test Set 

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size = 0.2)

C:\Users\bhale\Downloads\anaconda\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [4]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train=sc.fit_transform(X_train) 
X_test=sc.transform(X_test)


In [5]:
#Training the Naive Bayes Classification model on the Training Set

from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB() 
classifier.fit(X_train, y_train)

GaussianNB()

In [6]:
#Predicting the Test set results

y_pred = classifier.predict(X_test)

print(y_pred)


['Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica']


In [7]:
#Confusion Matrix and Accuracy

from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
from sklearn.metrics import accuracy_score 
print("Accuracy : ", accuracy_score(y_test,y_pred)) 
print(cm)


Accuracy :  1.0
[[13  0  0]
 [ 0  2  0]
 [ 0  0 15]]


In [8]:
#Comparing the Real Values with Predicted Values

df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

        Real Values Predicted Values
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5    Iris-virginica   Iris-virginica
6       Iris-setosa      Iris-setosa
7    Iris-virginica   Iris-virginica
8    Iris-virginica   Iris-virginica
9       Iris-setosa      Iris-setosa
10   Iris-virginica   Iris-virginica
11   Iris-virginica   Iris-virginica
12   Iris-virginica   Iris-virginica
13   Iris-virginica   Iris-virginica
14   Iris-virginica   Iris-virginica
15      Iris-setosa      Iris-setosa
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20      Iris-setosa      Iris-setosa
21      Iris-setosa      Iris-setosa
22   Iris-virginica   Iris-virginica
23   Iris-virginica   Iris-virginica
24  Iris-versicolor  Iris-versicolor
25      Iris-setosa      Iris-setosa
2

In [9]:
#Compute Error rate, Precision and Recall

from sklearn.metrics import precision_score, recall_score, accuracy_score 

In [10]:
#Precision Score

print('Precision:',precision_score(y_test,y_pred,average='micro'))

Precision: 1.0


In [11]:
#Recall Score

print("Recall Score:",recall_score(y_test,y_pred,average='micro'))

Recall Score: 1.0
